samples: config/samples.tsv

units: config/units.tsv

ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 98
  # Ensembl release to use for SnpEff annotation (sometimes, the latest Ensembl release is not available in SnpEff)
  snpeff_release: 86
  # Genome build
  build: GRCh38

# Estimation of tumor mutational burden.
tmb:
  activate: false
  # Size of the sequenced coding genome for TMB estimation
  # Attention: when doing panel sequencing, set this to the
  # CAPTURED coding genome, not the entire one!
  coding_genome_size: 3e7
  # Name of the tumor sample in the scenario.yaml.
  tumor_sample: tumor
  somatic_events:
    - SOMATIC_TUMOR_LOW
    - SOMATIC_TUMOR_MEDIUM
    - SOMATIC_TUMOR_HIGH

calling:
  delly:
    activate: true
  freebayes:
    activate: true
  # See https://varlociraptor.github.io/docs/calling/#generic-variant-calling
  scenario: config/scenario.yaml
  # See http://snpeff.sourceforge.net/SnpSift.html#filter
  filter:
    # add any number of named filters here. They will be applied independenty,
    # and can be referred in FDR control below to generate calls for different events.
    filtername: "ANN[*].IMPACT has 'MODERATE'"
  fdr-control:
    threshold: 0.05
    events: 
      # Add any number of events here to filter for.
      present:
        varlociraptor: 
          - "PRESENT"
        filter: filtername

annotations:
  dbnsfp:
    activate: false
  vcfs:
    activate: true
    # annotate with known variants from ensembl
    known: refs/variation.vcf.gz
    # add more external VCFs as needed
    # cosmic: path/to/cosmic.vcf.gz
  dgidb:
    activate: true

params:
  cutadapt: ""
  picard:
    MarkDuplicates: ""
  gatk:
    BaseRecalibrator: ""
