samples:
  tumor:
    resolution: 100
    universe: "[0.0,1.0]"
    contamination:
      by: normal
      fraction: {{ 1.0 - samples[samples["alias"] == "tumor"]["purity"][0] }}
  normal:
    resolution: 5
    universe: "0.0 | 0.5 | 1.0 | ]0.0,0.5["

events:
  somatic_tumor_low: "tumor:]0.0,0.1[ & normal:0.0"
  somatic_tumor_medium: "tumor:[0.1,0.3[ & normal:0.0"
  somatic_tumor_high: "tumor:[0.3,1.0] & normal:0.0"
  somatic_normal: "normal:]0.0,0.5["
  germline_hom: "normal:1.0"
  germline_het: "normal:0.5"
